### ISSUE TITLE
Is 1.6.1 broken somehow?

### ISSUE THREAD

**Issue by akorchev** [zzzprojects/System.Linq.Dynamic.Core#892]
We have code that looks like this and builds just fine with 1.6.0:

```
     System.Linq.Dynamic.Core.ParsingConfig.Default.AllowEqualsAndToStringMethodsOnObject = true;
```

After upgrading to 1.6.1 this code no longer compiles:

```
error CS1061: 'ParsingConfig' does not contain a definition for 'AllowEqualsAndToStringMethodsOnObject'
```

What gives? I can clearly see it in the source: https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/ParsingConfig.cs#L321

**Comment by akorchev** [comment]
I am seeing things. There is no such version as 1.6.1 (although nuget resolves it to something).

**Comment by StefH** [comment]
1.6.1 is a wrong version which is unlisted

**Comment by StefH** [comment]
You can use 1.6.0.1 as latest

**Comment by akorchev** [comment]
> 1.6.1 is a wrong version which is unlisted

Thank you for confirming that. I thought I went insane.
